services:
  postgres:
    container_name: db
    image: 'postgres:16.3'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=secretpwd123'
    ports:
      - 5432:5432