app:
  currency-beacon:
    base-url: https://api.currencybeacon.com/v1
    api-key: ${CURRENCY_BEACON_KEY}

spring:
  application:
    name: account-service
  jpa:
    generate-ddl: false
    hibernate:
#      ddl-auto: validate